spring:
  application:
    name: PatientPortalDevConsoleApi
  main:
    banner-mode: console
    allow-bean-definition-overriding: false
  # Database and JPA configuration
  datasource:
    jndi-name: java:/PMRDatasource
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

management:
  endpoints:
    web:
      base-path: "/"
