spring:
  application:
    name: PatientPortalDevConsoleApi
  main:
    banner-mode: console
    allow-bean-definition-overriding: false
  # Database and JPA configuration
  spring:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://pp-v1-patientportal-data-service-ro-qa.dbc.chenmed.local:3306/
      username: aws_ppd_ro_qa
      password: w3LkKXcMbL7TnFAF
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true

management:
  endpoints:
    web:
      base-path: "/"
